{
 "title": "Resilience4j - Circuit Breaker (externalApi)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Circuit State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{name=\"externalApi\"} == 1",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{name=\"externalApi\"} == 1",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Bulkhead Saturation",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (resilience4j_bulkhead_available_concurrent_calls{name=\"externalApi\"} / resilience4j_bulkhead_max_allowed_concurrent_calls{name=\"externalApi\"})"
    }
   ]
  },
  {
   "title": "Calls per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by (kind)(rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"externalApi\"}[1m]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Failure Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"externalApi\",kind=\"failed\"}[1m])) / sum(rate(resilience4j_circuitbreaker_calls_seconds_count{name=\"externalApi\"}[1m])) * 100"
    }
   ]
  }
 ]
}